# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [2]:
# Write your answer here
import numpy as np
zeros=np.zeros(10, dtype=int)
print(zeros)

vowel=np.array(['a', 'e', 'o', 'i', 'u'])
print(vowel)

ones= np.array([[1,1,1,1,1],[1,1,1,1,1]])
print(ones)

one2= np.ones(10, dtype=int).reshape(2,5)
print(one2)

## numpy nested list means np.array
myarray1=np.array([[2.7,  0,  -2],[3.4,  10.6,  0],[-19, 99.9, 13]]) #this is nested
myarray1=np.array([2.7,  0,  -2, 3.4,  10.6,  0,-19, 99.9, 13]).reshape(3,3)
print(myarray1)

#start velue+ total value times step
myarray2=np.arange(4,4+15*4,4, dtype= float).reshape(3,5)
print(myarray2)

[0 0 0 0 0 0 0 0 0 0]
['a' 'e' 'o' 'i' 'u']
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [4]:
#Write your answer here
# 1
# itemsize how many bytes ... for each element in the arrray takes 8 bytes 
zeros.shape, zeros.size , zeros.ndim, zeros.dtype, zeros.itemsize
ones.shape, ones.size , ones.ndim, ones.dtype, ones.itemsize
myarray1.shape, myarray1.size , myarray1.ndim, myarray1.dtype, myarray1.itemsize
myarray2.shape, myarray2.size , myarray2.ndim, myarray2.dtype, myarray2.itemsize

# 2
ones=ones.reshape(1,10)
ones

# 3
vowel[1:3]

# 4
myarray1[1:3,]#[row:col]
myarray1[1:3,0:2]

# 5
myarray1[:, 0:2]#all rows, specific cols

# 6
myarray1[ 1:3 , 0:1 ]


# 7
vowel[:: -1]
# from the begainning to the end and the step= -1
# or use reverse

# abc=np.array(['a', 'b', 'c', 'd', 'e'])
# abc[:: -1]

array(['u', 'i', 'o', 'e', 'a'], dtype='<U1')

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [6]:
# Write your answer here
# 1
ones/3

# 2
myarray2[:, :3] +myarray1

# 3


# 7
( myarray1**3 )/2

# 8

np.round(np.sqrt(myarray2)/2)


array([[1., 1., 2., 2., 2.],
       [2., 3., 3., 3., 3.],
       [3., 3., 4., 4., 4.]])

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [8]:
# Write your answer here

# 1
myarray2.T
# or
np.transpose(myarray2)

# 2 
# vowel
np.sort(myarray1)#sort row by row, but col no
np.sort(myarray1, 1)#sort by row
np.sort(myarray1, 0)#sort by col




array([[-19. ,   0. ,  -2. ],
       [  2.7,  10.6,   0. ],
       [  3.4,  99.9,  13. ]])

Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [10]:
# Write your answer here
# -1 + step size*num of elements
myarray4 = np.arange(-1, -1 + 0.25*42 , 0.25).reshape(14, 3)
# myarray4.size

np.array_split(myarray4,3) #3 arrays



[array([[-1.  , -0.75, -0.5 ],
        [-0.25,  0.  ,  0.25],
        [ 0.5 ,  0.75,  1.  ],
        [ 1.25,  1.5 ,  1.75],
        [ 2.  ,  2.25,  2.5 ]]),
 array([[2.75, 3.  , 3.25],
        [3.5 , 3.75, 4.  ],
        [4.25, 4.5 , 4.75],
        [5.  , 5.25, 5.5 ],
        [5.75, 6.  , 6.25]]),
 array([[6.5 , 6.75, 7.  ],
        [7.25, 7.5 , 7.75],
        [8.  , 8.25, 8.5 ],
        [8.75, 9.  , 9.25]])]

Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [12]:
# Write your ansewr here
#1
np.sum(myarray4)

# 2



173.25

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [18]:
pip install html5lib


Note: you may need to restart the kernel to use updated packages.


In [25]:
# Write your answer here
import pandas as pd 

capitals= pd.read_csv("/Users/shomokh/Desktop/SENIOR1🥳🥳🥳/DS/country-capital-lat-long-population.csv")
capitals.head()

Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770   
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577   
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542   
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526   
4         Andorra       Andorra la Vella   42.5078     1.5211       22614   

  Capital Type  
0      Capital  
1      Capital  
2      Capital  
3      Capital  
4      Capital

In [ ]:
#NumPy arrays are faster and more efficient for numerical computations compared to Pandas DataFrames. Since you'll need to calculate Euclidean distances between coordinates, it's convenient to work with NumPy arrays for mathematical operations like subtraction, squaring, and summing.

In [67]:
capitals[capitals["Country"]== "Saudi Arabia"]

Country        Capital City  Latitude  Longitude  Population  \
182  Saudi Arabia  Ar-Riyadh (Riyadh)   24.6905    46.7096     6906595   

    Capital Type  
182      Capital

In [69]:
capitals[(capitals["Country"]== "Saudi Arabia") & (capitals["Capital City"]== "Ar-Riyadh (Riyadh)")]

Country        Capital City  Latitude  Longitude  Population  \
182  Saudi Arabia  Ar-Riyadh (Riyadh)   24.6905    46.7096     6906595   

    Capital Type  
182      Capital

In [75]:
#2
# Extract Riyadh's coordinates
riyadh = capitals[capitals['Capital City'] == 'Ar-Riyadh (Riyadh)'][['Latitude', 'Longitude']].to_numpy()

# Extract coordinates of all other capital cities (excluding Riyadh)
other_capitals = capitals[capitals['Capital City'] != 'Ar-Riyadh (Riyadh)'][['Latitude', 'Longitude']].to_numpy()



In [81]:
#3
# Now, use broadcasting to compute the Euclidean distance
distances = np.sqrt(((other_capitals - riyadh) ** 2).sum(axis=1))

# Find the index of the closest capital city
#argmin: find the index of the minimum value
closest_index = np.argmin(distances)


#capitals.iloc[closest_index]: This accesses the row in the DataFrame corresponding to the index of the closest capital city.
#['Capital']: This selects the value in the 'Capital' column for that row.
closest_city = capitals.iloc[closest_index]['Capital City']
print(f"The closest capital city to Riyadh is {closest_city}.")

The closest capital city to Riyadh is Al-Manamah (Manama).


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [89]:
# Write your answer here
capitals[capitals["Country"].str.startswith("U", na=False)]


Country          Capital City  Latitude  Longitude  \
217                        Uganda               Kampala    0.3163    32.5822   
218                       Ukraine           Kyiv (Kiev)   50.4454    30.5186   
219          United Arab Emirates  Abu Zaby (Abu Dhabi)   24.4648    54.3618   
220                United Kingdom                London   51.5085    -0.1257   
221   United Republic of Tanzania                Dodoma   -6.1722    35.7395   
222      United States of America      Washington, D.C.   38.8951   -77.0364   
223  United States Virgin Islands      Charlotte Amalie   18.3419   -64.9307   
224                       Uruguay            Montevideo  -34.8335   -56.1674   
225                    Uzbekistan              Tashkent   41.2647    69.2163   

     Population Capital Type  
217     2986352      Capital  
218     2956706      Capital  
219     1419699      Capital  
220     9046485      Capital  
221      261645      Capital  
222     5206593      Capital  
223       52322      Capital  
224     1736989      Capital  
225     2463969      Capital

In [95]:
capitals[(capitals["Country"]== "United States of America") & (capitals["Capital City"]== "Washington, D.C.")]

Country      Capital City  Latitude  Longitude  \
222  United States of America  Washington, D.C.   38.8951   -77.0364   

     Population Capital Type  
222     5206593      Capital

In [97]:
# Extract washington's coordinates
washington = capitals[capitals['Capital City'] == 'Washington, D.C.'][['Latitude', 'Longitude']].to_numpy()

# Extract coordinates of all other capital cities (excluding Riyadh)
other_capitals = capitals[capitals['Capital City'] != 'Washington, D.C.'][['Latitude', 'Longitude']].to_numpy()



In [99]:
# Now, use broadcasting to compute the Euclidean distance
distances = np.sqrt(((other_capitals - riyadh) ** 2).sum(axis=1))

# Find the index of the closest capital city
#argmin: find the index of the minimum value
closest_index = np.argmin(distances)


#capitals.iloc[closest_index]: This accesses the row in the DataFrame corresponding to the index of the closest capital city.
#['Capital']: This selects the value in the 'Capital' column for that row.
closest_city = capitals.iloc[closest_index]['Capital City']
print(f"The closest capital city to Washington is {closest_city}.")

The closest capital city to Riyadh is Ar-Riyadh (Riyadh).
